### ISSUE TITLE
Reformat Buy/Sell Page

### ISSUE THREAD

**Issue by easydeze** [easydeze/comp413-fe#11]
The current iteration squishes the buy/sell form too much. Let's display it in a more visually appealing manner like below:

<img width="375" alt="Screenshot 2024-11-01 at 1 59 18 PM" src="https://github.com/user-attachments/assets/8ed610a0-02a2-4a01-b177-99177c5cef3d">

**Comment by mikayBuk** [comment]
Update is commit to BuySell-http branch
